apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: roboshop
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: cm9ib3Nob3A=
  RABBITMQ_DEFAULT_PASS: cm9ib3Nob3AxMjM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels: 
    app: rabbitmq
    project: roboshop
    db : app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
      project: roboshop
      db : app
  template:
    metadata:
      labels:
        app: rabbitmq
        project: roboshop
        db : app
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq 
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    app: rabbitmq
    project: roboshop
    db : app
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    


