apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data:
  MYSQL_DATABASE: "cities"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: roboshop
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Um9ib1Nob3BAMQ==
  MYSQL_USER: c2hpcHBpbmc=
  MYSQL_PASSWORD: Um9ib1Nob3BAMQ==
---
apiVersion: apps/v1
kind: Deployment    # deplyment defination
metadata:
  name: mysql
  namespace: roboshop
  labels:
    app: mysql
    project: roboshop
    tier: db

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      project: roboshop
      tier: db
  template:           # pod defination starts
    metadata:
      labels:
        app: mysql
        project: roboshop
        tier: db
    spec:
      containers:
      - name: mysql
        image: narupallearun/mysql:v1
        imagePullPolicy: Always
---
apiVersion: v1 
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    app: mysql
    project: roboshop
    tier: db
  ports:
  - protocol: TCP
    port : 3306
    targetPort: 3306
