apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
  namespace: roboshop
data:
  MONGO : "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels: 
    app: redis
    project: roboshop
    db : app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      project: roboshop
      db : app
  template:
    metadata:
      labels:
        app: redis
        project: roboshop
        db : app
    spec:
      containers:
      - name: redis
        image: narupallearun/redis:v1  
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    app: redis
    project: roboshop
    db : app
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    


